version: "3.2"
services:
  zookeeper:
    build: ./zookeeper
    restart: always
    command:
      - "start-foreground"
    ports:
      - "2181:2181"

  kafka:
    build: ./kafka
    restart: always
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=192.168.0.106
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=customer:1:1,audit:1:1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=1099
      - JMX_PORT=1099

  kafka-exporter:
    image: danielqsj/kafka-exporter
    restart: always
    links:
      - kafka
    depends_on:
      - kafka
    ports:
      - "9308:9308"
    command: --kafka.server=kafka:9092

  jmxexporter:
    image: sscaling/jmx-prometheus-exporter
    ports:
      - "5556:5556"
    environment:
      SERVICE_PORT: 5556
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - ./kafka/prom-jmx-agent-config.yml:/opt/jmx_exporter/config.yml

  prometheus:
    build: ./prometheus
    restart: always
    links:
      - kafka-exporter
      - jmxexporter
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    restart: always
    depends_on:
      - prometheus
    links:
      - prometheus
    ports:
      - 3000:3000
